"""Remove temporary files generated by benchmarks."""

from __future__ import annotations

import shutil
from pathlib import Path

TEMP_DIRS = [
    Path("results") / "fileio-temp",
    Path(".uv-cache"),
]

TEMP_PATTERNS = [
    ("results", "*.prof"),
]


def main() -> int:
    removed = 0

    for directory in TEMP_DIRS:
        if directory.exists():
            count = sum(1 for _ in directory.iterdir())
            shutil.rmtree(directory)
            print(f"removed {directory}/ ({count} files)")
            removed += count

    for parent, pattern in TEMP_PATTERNS:
        for path in Path(parent).glob(pattern):
            path.unlink()
            print(f"removed {path}")
            removed += 1

    if removed == 0:
        print("nothing to clean")
    else:
        print(f"\ncleaned {removed} file(s)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
